server:
  port: 8090
  shutdown: graceful

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:9001/
          predicates:
            - Path=/auth/**
        - id: token-service
          uri: http://localhost:9002/
          predicates:
            - Path=/token/**
        - id: backend-service
          uri: http://localhost:9003/
          predicates:
            - Path=/api/**
  profiles:
    active: local

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_USERNAME}:${EUREKA_PASSWORD}@localhost:8761/eureka