server:
  port: 8090
  shutdown: graceful

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        - id: token-service
          uri: lb://token-service
          predicates:
            - Path=/token/**

        - id: backend-service
          uri: lb://backend-service
          predicates:
            - Path=/api/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://www.caboomlog.site:80"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka

custom-filter:
  whitelist:
    jwt:
      - /login
      - /signup
      - /token/refresh
      - /topic/**
      - /api/blogs/*