name: gateway-service ci/cd

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: |
          ./mvnw clean package -DskipTests

      - name: Copy to Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "==> Removing old files..."
            sudo rm -rf ~/gateway-service
            
            echo "==> Creating gateway-service directory..."
            sudo mkdir -p ~/gateway-service
            sudo chmod -R 777 ~/gateway-service
            
            echo "==> Cloning repository..."
            sudo git clone https://github.com/caboom-log/gateway-service.git ~/gateway-service
            
            cd ~/gateway-service
            
            echo "==> Preparing target directory..."
            sudo mkdir -p target/classes
            sudo chmod -R 777 target
            
            echo "==> Building gateway service..."
            sudo ./mvnw clean package -DskipTests
            
            echo "==> Building Docker image..."
            sudo docker build -t caboomlog-gateway-service:latest .
            
            echo "==> Restarting gateway-service..."
            cd /caboomlog
            sudo docker-compose --env-file ./gateway-service/.env restart gateway-service

